#copyright @ Eko India Financial Service Pvt. Ltd.
from __future__ import unicode_literals

#TODO: global and immutable constant test 
# Master Agent Type
AGENT_TYPE_DISTRIBUTOR = 3
AGENT_TYPE_RETAILER = 4
AGENT_TYPE_FOS = 5
AGENT_TYPE_ICSP = 7

# Master User Type
USER_TYPE_AGENT = 1
USER_TYPE_TYPE2 = 2
USER_TYPE_TYPE3 = 3
USER_TYPE_TYPE4 = 4

# Cellnumber Types
CELLNUMBER_TYPE_PRIMARY = 1
CELLNUMBER_TYPE_ALTERNATE1 = 2

# Master Bank 
BANK_SBI = 1
BANK_ICICI = 2
BANK_YBL = 3
PPI = 4

# Transaction Type

TRXN_SENDER_INQUIRY = 2
TRXN_SENDER_ENROLMENT = 16
TRXN_SENDER_ENROLMENT_VERIFIC = 3
TRXN_SENDER_ENROLMENT_RESEND_OTP = 4
TRXN_RECIPIENT_REG = 15
TRXN_RECIPIENT_REG_VERIFIC = 17
TRXN_RECIPIENT_REG_RESEND_OTP = 18
TRXN_REGISTERED_RECIPIENT_INQUIRY = 14
TRXN_MONEY_TRANSFER = 13
TRXN_BALANCE_INQUIRY = 12
TRXN_RECIPIENT_INDIVIDUAL_INQUIRY = 11
TRXN_ACCOUNT_NUMBER_LOOKUP = 10
TRXN_USER_INFO_LOOKUP = 9
TRXN_SOS_INQUIRY = 8
TRXN_BOOKLET_REGISTRATION = 7
TRXN_BOOKLET_INQUIRY = 6
TRXN_BANK_CONFIG_INQUIRY = 5
TRXN_AGREEMENT_CONSENT = 20
TRXN_RESEND_TX_OTP = 19
TRXN_RECIPIENT_MIGRATION = 22

TRXN_ENQ=1
TRXN_CBS_INQUIRY=23

#Contact type constants
CONTACT_TYPE_PRIMARY = 1
CONTACT_TYPE_SECONDARY = 2

#Bank Name Constant
SBI_BANK_SHORT_NAME = 'SBI'
ICICI_BANK_SHORT_NAME = 'ICICI'
YES_BANK_SHORT_NAME = 'YBL'

#Response type ids constants
ENROLMENT_VERIFICATION_PENDING = 327
ENROLLMENT_SUCCESS = 300
ALREADY_ENROLED = 17
NO_RECIPIENT = 22
RECIPIENT_FOUND = 23
INVALID_ACCOUNT_NUM = 149
INVALID_IFSC = 342
RECIPIENT_REG_SUCCESS = 42
REC_REG_SUCCESS = 43
SUCCESS_INQUIRY = 18
VERIFICATION_PENDING = 37
INCORRECT_PIN = 64
INVALID_OKKEY = 62
TX_SUCCESS = 325
NON_KYC_ACTIVE = 33
RECIPIENT_VERIFIED = 61
RECIPIENT_VERIFICATION_INVALID_ACC_NUM = 46
RECIPIENT_VERIFICATION_INVALID_IFSC = 543
REC_VERIFICATION_INVALID_IFSC = 44
RECIPIENT_ALREADY_REGISTERED = 345
BANK_CONFIG_INQUIRY_SUCCESS = 466
REG_FAILED_INVALID_IFSC = 45
SUCCESS = 0
ERROR = -1
FAILURE = 1

#status

#in user module
ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
ACCOUNT_ACTIVE_FIRST_LOGIN = "ACCOUNT_ACTIVE_FIRST_LOGIN"
SUCCESS_STATUS = "SUCCESS_STATUS"

#responsehandler status

UNKNOWN_STATUS = "UNKNOWN_STATUS"
VERIFICATION_PENDING_STATUS = "VERIFICATION_PENDING"

#IN TRANSACTION RESPONSEHANDLER 
BOOKLET_REG_SUCCESS_STATUS='BOOKLET_REG_SUCCESS'
BOOKLET_REG_FAILED_INCORRECT_FORMAT_STATUS='BOOKLET_REG_FAILED_INCORRECT_FORMAT'
BOOKLET_REG_FAILED_STATUS='BOOKLET_REG_FAILED'
SUCCESS_DISP = 'SUCCESS'
FAILURE_DISP = 'FAILURE'
TRXN_NOT_ALLOWED_STATUS = "TRXN_NOT_ALLOWED"
CONN_ERROR_STATUS = "CONN_ERROR"
APPLIC_ERROR_STATUS = "APPLIC_ERROR"
TRXN_IN_PROGRESS_STATUS	 = "TRXN_IN_PROGRESS"
INCORRECT_PIN_STATUS = "INCORRECT_PIN"
ENROLLED_STATUS = "ENROLLED"
NOT_ENROLLED_STATUS = "NOT_ENROLLED" 
BANK_CONFIG_INQUIRY_SUCCESS_STATUS = 'BANK_CONFIG_INQUIRY_SUCCESS'
BANK_CONFIG_INQUIRY_FAILED_STATUS = 'BANK_CONFIG_INQUIRY_FAILED'
OTP_VERIFIC_PENDING_STATUS = "OTP_VERIFIC_PENDING"
NON_KYC_ACTIVE_STATUS ="NON_KYC_ACTIVE"
ENQR_SUCCESS_STATUS ="ENQR_SUCCESS"
ENQR_FAILED_STATUS = "ENQR_FAILED"
FOUND_RECIPIENTS_STATUS =  "FOUND_RECIPIENTS"
NO_RECIPIENTS_STATUS = "NO_RECIPIENTS" 
RECIPIENT_INQUIRY_ERROR_STATUS = "RECIPIENT_INQUIRY_ERROR"
ENROLMENT_FAILED_STATUS = "ENROLMENT_FAILED"
ENROLMENT_OTP_VERIFICATION_SUCCESS_STATUS = "ENROLMENT_OTP_VERIFICATION_SUCCESS"
RECIPIENT_REG_FAILED_INVALID_ACCOUNT_NUM_STATUS = "RECIPIENT_REG_FAILED_INVALID_ACCOUNT_NUM"
RECIPIENT_REG_FAILED_INVALID_IFSC_STATUS = "RECIPIENT_REG_FAILED_INVALID_IFSC"
RECIPIENT_ALREADY_REGISTERED_STATUS = "RECIPIENT_ALREADY_REGISTERED"
RECIPIENT_REG_SUCCESS_STATUS = "RECIPIENT_REG_SUCCESS"
RECIPIENT_REG_FAILED_STATUS = "RECIPIENT_REG_FAILED"
RECIPIENT_VERF_SUCCESS_STATUS = "RECIPIENT_VERF_SUCCESS"
RECIPIENT_VERF_FAILED_STATUS = "RECIPIENT_VERF_FAILED"
RECIPIENT_VERIFIED_STATUS = "RECIPIENT_VERIFIED"
RECIPIENT_VERIFICATION_FAILED_INVALID_ACCOUNT_NUM_STATUS = "RECIPIENT_VERIFICATION_FAILED_INVALID_ACCOUNT_NUM"
RECIPIENT_VERIFICATION_FAILED_INVALID_IFSC_STATUS = "RECIPIENT_VERIFICATION_FAILED_INVALID_IFSC"
RECIPIENT_VERIFICATION_FAILED_STATUS = "RECIPIENT_VERIFICATION_FAILED"
RECIPIENT_VERIFICTION_PENDING_STATUS = "RECIPIENT_VERIFICTION_PENDING"
SERVICE_UNAVAILABLE_STATUS = "SERVICE_UNAVAILABLE"  
INVALID_USER_STATUS = "INVALID_USER"
REQUEST_TIMEOUT_STATUS = "REQUEST_TIMEOUT"
FAILED_STATUS = "FAILED"
AGREEMENT_PENDING_STATUS = "AGREEMENT_PENDING"
OKEKEY_BLOCKED_STATUS = 'OKEKEY_BLOCKED'
SOS_RESPONSE_AVAILABLE_STATUS = 'SOS_RESPONSE_AVAILABLE'
SOS_RESPONSE_NOT_AVAILABLE_STATUS = 'SOS_RESPONSE_NOT_AVAILABLE'
SOS_FAILED_STATUS = 'SOS_FAILED'
BOOKLET_INQUIRY_SUCCESS_STATUS = 'BOOKLET_INQUIRY_SUCCESS'
BOOKLET_INQUIRY_FAILED_STATUS = 'BOOKLET_INQUIRY_FAILED'
ENROLMENT_SUCCESS_STATUS = "ENROLMENT_SUCCESS"
ALREADY_ENROLED_STATUS = "ALREADY_ENROLED"